---
title: "IS 609 Week 12 Homework"
author: "Ben Arancibia"
date: "November 11, 2015"
output:
  pdf_document: default
---

__576__

2) Consider a company that allows back ordering. That is, the company notifies customers that a temporary stock-out exists and that their order will be filled shortly. What conditions might argue for such a policy? What effect does such a policy have on storage costs? Should costs be assigned to stock-outs? Why? How would you make such an assignment? What assumptions are implied by the model in Figure 13.7? Suppose a "loss of goodwill cost" of w dollars per unit per day is assigned to each stock-out. Compute the optimal order quantity Q* and interpret your model.


Conditions that might argue for such a policy are if storage costs are high and delivery costs are low. This might result in a back-ordering policy. This type of policy would lower average storage cost per unit as a result of pre-sold items. The effect that this policy has on storage costs is that pre-sold items would have a 0 storage cost, and would lower the average storage cost per item.

Should costs be assigned to stock-outs? Why?
If costs should be assigned to stock-outs depends on the customer's perception of the stock-out. If they are unhappy and might take their business to another supplier, then yes. Otherwise, no costs should not be assigned to stock-outs.

How would you make such an assignment?

To assign stock-out costs, they have to quantified: number of units demanded below zero times some cost g, negative stock buffer qb

w = 0 
w = qt * g

qt >= 0
qt <= 0

the cost per cycle is:

d + s(q/2)t + w

What assumptions are implied by the model in Figure 13.7?

The assumptions applied assumes instant stock on delivery and regular depletion of stock over the course of a cycle. 



__591__

5) Find the hottest point (x,y,z) along the ellipitcal orbit

4x^2 + y^2 + 4z^2 = 16

where the temperature function is

T(x,y,z) = 8x^2 + 4yz - 16z + 600

Using the Lagrangian Multiplier technique:

[L(x,y,z,\lambda)=8x^2+4yz-16z+600 + \lambda[4x^2+y^2+4z^2-16]]

Next, we find the partial derivatives of (L) with respect to each variable:

[\frac{\partial L}{\partial x} = 16x + 8x\lambda]

[\frac{\partial L}{\partial y} = 4z + 2 \lambda y]

[\frac{\partial L}{\partial z} = 4y - 16 + 8 \lambda z]

[\frac{\partial L}{\partial \lambda} = 4x^2 + y^2 + 4z^2 - 16]

Solving the equations for 0 we get (x=0, y=\frac{-2z}{\lambda}=\frac{-4}{\lambda^2-1}, z=\frac{2\lambda}{\lambda^2-1}, \text{ and } \lambda=0 ).

Plugging in these values:

(x=0, y=4, z=0, \text{ and } \lambda=0 )

[L(0,4,0,0)=8(0)^2+4(4)(0)-16(0)+600 + (0)[4x^2+y^2+4z^2-16] = 600]


_599_

5) One of the key assumptions underlying the models developed in this section is that the harvest rate equals the growth rate for a sustained yield. The reprodcution submodels in Figures 13.19 and 13.22 suggest that if the current population levels are known, it is possible to estimate the growth rate. The implication of this knowledge is that if a quota for the season is established based on the estimated growth rate, then the fish population can be maintained, increased, or decreased as desired. This quota system might be implemented by requiring all commercial fisherman to register their catch daily and then closing the season when the quota is reached.






